### ISSUE TITLE
problems with item order in a sequence

### ISSUE THREAD

**Issue by hw-du** [DyGRec/ASReP#2]
When I try to pretrain your model to yield pseudo items, it seems that in your code, the actual item order in a sequence  is inconsistent with the proposed model in your paper.
For example, assume you have a sequence with items [1,2,3,4,5,6]. When you try to reverse-train the model, you should input [6,5,4,3,2] as training user sequence and [5,4,3,2,1] as positive user sequence. But when I try to examine this, I get very confusing sequence like [5,4,2,1,3].
```
def sample_function(user_train, usernum, itemnum, batch_size, maxlen, result_queue, SEED):
    def sample():
        user = np.random.randint(1, usernum + 1)
        while len(user_train[user]) <= 1: user = np.random.randint(1, usernum + 1)

        seq = np.zeros([maxlen], dtype=np.int32)
        pos = np.zeros([maxlen], dtype=np.int32)
        neg = np.zeros([maxlen], dtype=np.int32)
        nxt = user_train[user][-1]
        idx = maxlen - 1

        ts = set(user_train[user])
        for i in reversed(user_train[user][:-1]):
            seq[idx] = i
            pos[idx] = nxt
            if nxt != 0: neg[idx] = random_neq(1, itemnum + 1, ts)
            nxt = i
            idx -= 1
            if idx == -1: break

        return (user, seq, pos, neg)

    np.random.seed(SEED)
    while True:
        one_batch = []
        for i in range(batch_size):
            one_batch.append(sample())
            print(one_batch[-1]) #something went wrong here
        result_queue.put(zip(*one_batch))
```
What's more, the item order is also suspicious when I try to reverse-predict pseudo items based on trained model.
According to this code, train, test, valid, and cumulatively-predicted items are concatenated orderly and then fed into transformer model to yield next pseudo item. 
`u_data = train.get(u, []) + valid.get(u, []) + test.get(u, []) + cumulative_preds.get(u, [])`
But if you want to predict pseudo items, shouldn't you put cumulative predictions at the beginning of the original sequence so the order should be `u_data = cumulative_preds.get(u, [])+train.get(u, []) + valid.get(u, []) + test.get(u, [])` ?
Looking forward to your reply
Thanks

**Comment by zfan20** [comment]
Hi,

You might misunderstand the code. First, I cannot reproduce your errors and this part of the code is exactly from SASRec and you can check those out. For the second question, as there is one more reverse operation in the process of creating the sequence, you might also check it out to confirm your guess.

Best.
